@LearnApp.Server_HostAddress = http://localhost:5145

GET {{LearnApp.Server_HostAddress}}/api/User/get/1/123456
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/User/find/derstulu@gmail.com/123456
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/User/stats/1
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/User/public/1
Accept: application/json

###
GET {{LearnApp.Server_HostAddress}}/api/Lesson/fetch/15
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/Lesson/suggest/1/0/1
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/Lesson/user/1/0/10
Accept: application/json
###
GET {{LearnApp.Server_HostAddress}}/api/Lesson/search/Basics/1/0/10
Accept: application/json

